New feature; a 'pipe-headers' incoming filter file source.  Identical to 'pipe' except that it only pipes the headers to the program, instead of the headers + body.
For performance reasons, 'pipe-headers' should be used instead of
'pipe' unless the user absolutely needs to process the message body.

Also, this should fix the often reported IOError with 'pipe'
and large messages with broken programs that cause SIGPIPE. e.g,

IOError: [Errno 32] Broken pipe


git-svn-id: https://tmda.svn.sourceforge.net/svnroot/tmda/trunk@1889 2baf9af7-fe1d-0410-8d70-c10643b1d81c